name: Build and Test

on:
  pull_request:
    branches: 
      - 'develop'
      - main
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - 'develop'
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
